### ISSUE TITLE
Outflow e Inflow invertidos

### ISSUE THREAD

**Issue by guilhermesagas** [rubensflinco/nubank-ofx#2]
Cara, muito boa sua extensão! Mas eu preciso reconciliar cada entrada porque outflow e inflow estão invertidos.

O padrão seria:
outflow para gastos
inflow para pagamentos de fatura e créditos no cartão.

Abs!

**Comment by jeffersantoss** [comment]
Está invertido mesmo... alguma novidade?

**Comment by jeffersantoss** [comment]
Fiz a correção...
