### ISSUE TITLE
Outros bancos

### ISSUE THREAD

**Issue by renanmpimentel** [rubensflinco/nubank-ofx#3]
Cara, parabens pela ideia.. eu peguei um gancho do que fez, e apliquei o mesmo no santander..

https://gist.github.com/renanmpimentel/d07646fda10e924a1143c84a0bd6eeaf

Acha que rola fazermos algo para vários bancos ?

**Comment by tonicospinelli** [comment]
este repo tem o propósito apenas para o nubank, normalmente os bancos já fornecem esse recurso para exportar o extrato.
