### ISSUE TITLE
Fatura Aberta

### ISSUE THREAD

**Issue by douglas-mcosta** [rubensflinco/nubank-ofx#7]
Não esta mais funcionando com fatura aberta.
![image](https://user-images.githubusercontent.com/12072278/116830354-cf2d9780-ab7f-11eb-9369-f2f2547617ea.png)

**Comment by fdiaspp** [comment]
Oi Douglas, 

Percebi que quando acesso pela primeira vez a página da fatura em aberta, o botão não aparece. Porém, se atualizo a página, a funcionalidade é disponibilizada. 

Poderia testar por gentileza?

**Comment by rubensflinco** [comment]
Corrigido esse problema agora para faturas em aberto o botão também irá aparecer, e corrigi o problema de as vezes não aparecer o botão.
